In [31]:
import tensorflow as tf

In [34]:
import numpy as np

In [35]:
import os

In [17]:
batch_size = 32
img_height = 180
img_width = 180

In [27]:
class_names = ["masked", "not_masked"]

In [30]:
model = tf.keras.models.load_model('/Users/wisdom/Downloads')

In [45]:
sunflower_url = 'https://cdn.shopify.com/s/files/1/0257/9152/8994/products/20200416_184756_2_800x.jpg?v=1587430098'
sunflower_path = tf.keras.utils.get_file('not_m_3', origin=sunflower_url)

img = tf.keras.preprocessing.image.load_img(
    sunflower_path, target_size=(img_height, img_width)
)
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch
print(img_array)

predictions = model.predict(img_array)
score = tf.nn.softmax(predictions[0])

print(
    "This image most likely belongs to {} with a {:.2f} percent confidence."
    .format(class_names[np.argmax(score)], 100 * np.max(score))
)

tf.Tensor(
[[[[227. 223. 212.]
   [227. 223. 212.]
   [228. 224. 213.]
   ...
   [223. 216. 206.]
   [223. 216. 206.]
   [223. 216. 206.]]

  [[229. 224. 218.]
   [229. 224. 218.]
   [229. 224. 218.]
   ...
   [224. 217. 207.]
   [224. 217. 207.]
   [224. 217. 207.]]

  [[229. 224. 218.]
   [229. 224. 218.]
   [229. 224. 218.]
   ...
   [225. 218. 208.]
   [224. 217. 207.]
   [224. 217. 207.]]

  ...

  [[151.  61. 219.]
   [153.  58. 222.]
   [141.  46. 208.]
   ...
   [118.  21. 176.]
   [ 95.   0. 153.]
   [112.  11. 169.]]

  [[138.  41. 209.]
   [141.  42. 210.]
   [152.  52. 226.]
   ...
   [128.  37. 192.]
   [126.  32. 188.]
   [114.  19. 173.]]

  [[161.  65. 233.]
   [162.  65. 232.]
   [150.  48. 218.]
   ...
   [133.  39. 195.]
   [133.  39. 195.]
   [131.  40. 193.]]]], shape=(1, 180, 180, 3), dtype=float32)
This image most likely belongs to masked with a 100.00 percent confidence.


In [41]:
    parts = sunflower_url.split(os.path.sep)
    print(parts[-1])

20200416_184756_2_800x.jpg?v=1587430098
