In [13]:
import tensorflow as tf

In [14]:
%matplotlib inline

In [15]:
import numpy as np

In [16]:
import sys

In [17]:
import pickle

In [18]:
import matplotlib

In [19]:
! conda install numpy -y

Solving environment: done

# All requested packages already installed.



In [20]:
! conda install pandas

Solving environment: done

# All requested packages already installed.



In [21]:
import pandas as pd

In [22]:
hello = tf.constant('hello, world')

In [23]:
print(hello)

tf.Tensor(b'hello, world', shape=(), dtype=string)


In [24]:
sampleConstant = tf.constant(1 , tf.int16, name="sampleConstant")

In [25]:
print(sampleConstant)

tf.Tensor(1, shape=(), dtype=int16)


In [26]:
zeros = tf.zeros([10, 10], tf.int16)

In [27]:
print(zeros)

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]], shape=(10, 10), dtype=int16)


In [28]:
ones = tf.ones([10, 10], tf.int16)

In [29]:
tfAdd = tf.add(zeros, ones)

In [30]:
print(tfAdd)

tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]], shape=(10, 10), dtype=int16)


In [31]:
tfVar = tf.Variable(tfAdd)

In [73]:
pickle.dump(tfVar, open('train_test/tfVar.pickle', 'wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'train_test/tfVar.pickle'

In [32]:
numpyArr = np.array([1,2,3])

In [33]:
convertToTensor = tf.convert_to_tensor(numpyArr, tf.int16)

In [34]:
print(convertToTensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)


In [35]:
reduceAdd = tf.reduce_sum(convertToTensor)

In [36]:
print(reduceAdd)

tf.Tensor(6, shape=(), dtype=int16)


In [37]:
reduceAdd = tf.reduce_sum(tfAdd)

In [38]:
print(reduceAdd)

tf.Tensor(100, shape=(), dtype=int16)


In [39]:
reduceProd = tf.reduce_prod(convertToTensor)

In [40]:
print(reduceProd)

tf.Tensor(6, shape=(), dtype=int16)


In [41]:
reduceProd = tf.reduce_prod(tfAdd)

In [42]:
print(reduceProd)

tf.Tensor(1, shape=(), dtype=int16)


In [43]:
array = [[1,2], [3,4]]

In [44]:
npArray = np.array(array)

In [45]:
print(npArray)

[[1 2]
 [3 4]]


In [46]:
dataFrameArray = pd.DataFrame(array)

In [47]:
print(dataFrameArray)

   0  1
0  1  2
1  3  4


In [48]:
dict = {"name":["David", "Theophilus"], "age":[27, 29]}

In [49]:
pdDict = pd.DataFrame(data=dict)

In [50]:
print(pdDict)

         name  age
0       David   27
1  Theophilus   29


In [51]:
dateRange = pd.date_range('20210101', periods=6, freq="D")

In [52]:
print(dateRange)

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')


In [53]:
random = np.random.randn(6, 4)

In [54]:
print(random)

[[-0.31690045 -0.53435175 -0.11435103  0.21305971]
 [-0.19008099  1.17005956 -0.08992036  0.75519944]
 [ 0.68824046 -0.32355758  0.90454591 -2.23974216]
 [-1.45709372  0.14223249 -0.27244944 -0.65958029]
 [ 1.3282628   0.01510413 -0.59120453 -0.93277935]
 [-0.50039277  0.45844535  1.20563068  0.24246069]]


In [55]:
pdDateDataFrame = pd.DataFrame(random, index=dateRange, columns=["A", "B", "C", "D"])

In [56]:
print(pdDateDataFrame)

                   A         B         C         D
2021-01-01 -0.316900 -0.534352 -0.114351  0.213060
2021-01-02 -0.190081  1.170060 -0.089920  0.755199
2021-01-03  0.688240 -0.323558  0.904546 -2.239742
2021-01-04 -1.457094  0.142232 -0.272449 -0.659580
2021-01-05  1.328263  0.015104 -0.591205 -0.932779
2021-01-06 -0.500393  0.458445  1.205631  0.242461


In [57]:
print(pdDateDataFrame.head(n=3))

                   A         B         C         D
2021-01-01 -0.316900 -0.534352 -0.114351  0.213060
2021-01-02 -0.190081  1.170060 -0.089920  0.755199
2021-01-03  0.688240 -0.323558  0.904546 -2.239742


In [58]:
print(pdDateDataFrame.tail(n=3))

                   A         B         C         D
2021-01-04 -1.457094  0.142232 -0.272449 -0.659580
2021-01-05  1.328263  0.015104 -0.591205 -0.932779
2021-01-06 -0.500393  0.458445  1.205631  0.242461


In [59]:
print(pdDateDataFrame.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.074661  0.154655  0.173709 -0.436897
std    0.971039  0.607681  0.712126  1.081740
min   -1.457094 -0.534352 -0.591205 -2.239742
25%   -0.454520 -0.238892 -0.232925 -0.864480
50%   -0.253491  0.078668 -0.102136 -0.223260
75%    0.468660  0.379392  0.655929  0.235110
max    1.328263  1.170060  1.205631  0.755199


In [60]:
print(pdDateDataFrame["A"])

2021-01-01   -0.316900
2021-01-02   -0.190081
2021-01-03    0.688240
2021-01-04   -1.457094
2021-01-05    1.328263
2021-01-06   -0.500393
Freq: D, Name: A, dtype: float64


In [61]:
print(pdDateDataFrame[["A", "B"]])

                   A         B
2021-01-01 -0.316900 -0.534352
2021-01-02 -0.190081  1.170060
2021-01-03  0.688240 -0.323558
2021-01-04 -1.457094  0.142232
2021-01-05  1.328263  0.015104
2021-01-06 -0.500393  0.458445


In [62]:
print(pdDateDataFrame[0:3])

                   A         B         C         D
2021-01-01 -0.316900 -0.534352 -0.114351  0.213060
2021-01-02 -0.190081  1.170060 -0.089920  0.755199
2021-01-03  0.688240 -0.323558  0.904546 -2.239742


In [63]:
print(pdDateDataFrame.loc[:,['A','B']])

                   A         B
2021-01-01 -0.316900 -0.534352
2021-01-02 -0.190081  1.170060
2021-01-03  0.688240 -0.323558
2021-01-04 -1.457094  0.142232
2021-01-05  1.328263  0.015104
2021-01-06 -0.500393  0.458445


In [64]:
print(pdDateDataFrame.iloc[:2, :2])

                   A         B
2021-01-01 -0.316900 -0.534352
2021-01-02 -0.190081  1.170060


In [65]:
print(pdDateDataFrame.drop(columns= ["D"]))

                   A         B         C
2021-01-01 -0.316900 -0.534352 -0.114351
2021-01-02 -0.190081  1.170060 -0.089920
2021-01-03  0.688240 -0.323558  0.904546
2021-01-04 -1.457094  0.142232 -0.272449
2021-01-05  1.328263  0.015104 -0.591205
2021-01-06 -0.500393  0.458445  1.205631


In [66]:
print(pdDateDataFrame)

                   A         B         C         D
2021-01-01 -0.316900 -0.534352 -0.114351  0.213060
2021-01-02 -0.190081  1.170060 -0.089920  0.755199
2021-01-03  0.688240 -0.323558  0.904546 -2.239742
2021-01-04 -1.457094  0.142232 -0.272449 -0.659580
2021-01-05  1.328263  0.015104 -0.591205 -0.932779
2021-01-06 -0.500393  0.458445  1.205631  0.242461


In [67]:
COLUMNS = ['age','workclass', 'fnlwgt', 'education', 'education_num', 'marital',
           'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
           'hours_week', 'native_country', 'label']
PATH = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

In [68]:
csvDataFrame = pd.read_csv(PATH, sep=",", skipinitialspace=True, names=COLUMNS, index_col=False)

In [69]:
print(csvDataFrame)

       age         workclass  fnlwgt   education  education_num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

                  marital         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-manag

In [70]:
print(csvDataFrame.groupby(['label']).mean())

             age        fnlwgt  education_num  capital_gain  capital_loss  \
label                                                                       
<=50K  36.783738  190340.86517       9.595065    148.752468     53.142921   
>50K   44.249841  188005.00000      11.611657   4006.142456    195.001530   

       hours_week  
label              
<=50K   38.840210  
>50K    45.473026  


In [71]:
csvDataFrame.groupby(['label', 'marital', 'race'])['capital_gain'].max()

label  marital                race              
<=50K  Divorced               Amer-Indian-Eskimo     6849
                              Asian-Pac-Islander        0
                              Black                  6497
                              Other                     0
                              White                 34095
       Married-AF-spouse      White                  2653
       Married-civ-spouse     Amer-Indian-Eskimo     3908
                              Asian-Pac-Islander     5013
                              Black                 10566
                              Other                  4064
                              White                 41310
       Married-spouse-absent  Amer-Indian-Eskimo        0
                              Asian-Pac-Islander        0
                              Black                  4650
                              Other                     0
                              White                  6849
       Never-married   

In [72]:
df_plot = csvDataFrame.groupby(['label', 'marital'])['capital_gain'].mean().unstack()
df_plot

marital     Divorced  Married-AF-spouse  Married-civ-spouse  \
label                                                         
<=50K     140.544724         204.076923          219.249517   
>50K     5781.812095         729.800000         3678.163927   

marital  Married-spouse-absent  Never-married    Separated      Widowed  
label                                                                    
<=50K               106.559896      99.052492   117.190824   149.811674  
>50K               6836.647059    6137.576375  6614.727273  5071.117647